name: Auth Service CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start auth service
        run: |
          npm start &
          sleep 3

      - name: Health check
        run: curl --fail http://localhost:3000/health

  docker:
    needs: test
    runs-on: ubuntu-latest
     environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN_POS }}

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/auth-service-cicd-poc:latest .

      - name: Push Docker image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/auth-service-cicd-poc:latest